-- Insert DJs
INSERT INTO public.djs (slug, name, stage_name, bio, image_url, genres, experience, rating, booking_rate, location, equipment, social_media, mix_samples, availability, residencies, achievements) VALUES
('nicky-nice', 'Nicholas Johnson', 'Nicky Nice', 'A versatile DJ with over 8 years of experience in house and techno music. Known for seamless mixing and reading the crowd perfectly.', '/professional-dj-mixing.png', ARRAY['House', 'Techno', 'Progressive'], 8, 4.8, 2500, 'Miami, FL', ARRAY['Pioneer CDJ-3000', 'DJM-900NXS2', 'KRK Rokit 8'], '{"instagram": "@nickynice_dj", "soundcloud": "nickynice", "twitter": "@nickynice"}', '[{"title": "Summer Vibes Mix", "url": "https://soundcloud.com/nickynice/summer-vibes", "duration": "45:30"}, {"title": "Techno Underground", "url": "https://soundcloud.com/nickynice/techno-underground", "duration": "52:15"}]', '{"monday": true, "tuesday": true, "wednesday": true, "thursday": true, "friday": true, "saturday": true, "sunday": true}', ARRAY['LIV Miami (Fridays)', 'Story Miami (Saturdays)'], ARRAY['Miami Music Week 2023 Headliner', 'Beatport Top 10 Remix']),

('tony-jack', 'Anthony Jackson', 'Tony Jack', 'Hip-hop specialist with incredible scratching skills and crowd interaction. Brings energy to every performance.', '/professional-dj-performing.png', ARRAY['Hip-Hop', 'R&B', 'Trap'], 6, 4.6, 2000, 'Atlanta, GA', ARRAY['Technics 1200', 'Serato DJ Pro', 'Shure SM58'], '{"instagram": "@tonyjack_official", "soundcloud": "tonyjackdj", "twitter": "@tonyjackdj"}', '[{"title": "Hip-Hop Classics", "url": "https://soundcloud.com/tonyjack/hiphop-classics", "duration": "38:45"}, {"title": "Trap Nation", "url": "https://soundcloud.com/tonyjack/trap-nation", "duration": "41:20"}]', '{"monday": false, "tuesday": false, "wednesday": true, "thursday": true, "friday": true, "saturday": true, "sunday": true}', ARRAY['Magic City (Thursdays)', 'Gold Room (Saturdays)'], ARRAY['Atlanta Hip-Hop Awards DJ of the Year', 'Collaborated with Local Rap Artists']),

('brotherhood', 'Marcus & David Williams', 'Brotherhood', 'Twin brothers who create an electrifying atmosphere with their synchronized performances and diverse music selection.', '/dj-duo-hip-hop.png', ARRAY['Hip-Hop', 'EDM', 'Pop'], 5, 4.7, 3000, 'Los Angeles, CA', ARRAY['Pioneer DDJ-SZ2', 'JBL PRX815W', 'Shure Beta 87A'], '{"instagram": "@brotherhood_djs", "soundcloud": "brotherhooddjs", "twitter": "@brotherhooddjs"}', '[{"title": "Brotherhood Live Set", "url": "https://soundcloud.com/brotherhood/live-set", "duration": "60:00"}, {"title": "EDM Explosion", "url": "https://soundcloud.com/brotherhood/edm-explosion", "duration": "35:30"}]', '{"monday": false, "tuesday": false, "wednesday": false, "thursday": true, "friday": true, "saturday": true, "sunday": false}', ARRAY['1 OAK LA (Fridays)', 'Avalon Hollywood (Saturdays)'], ARRAY['LA Music Awards Best DJ Duo', 'Coachella After-Party Performers']),

('trek', 'Trevor Kim', 'Trek', 'Techno purist with a passion for underground sounds. Creates immersive journeys through electronic music landscapes.', '/techno-dj-trek.png', ARRAY['Techno', 'Minimal', 'Industrial'], 7, 4.9, 2200, 'Detroit, MI', ARRAY['Allen & Heath Xone:96', 'Technics SL-1210MK7', 'Moog Subsequent 37'], '{"instagram": "@trek_techno", "soundcloud": "trektechno", "twitter": "@trektechno"}', '[{"title": "Underground Journey", "url": "https://soundcloud.com/trek/underground-journey", "duration": "75:00"}, {"title": "Minimal Madness", "url": "https://soundcloud.com/trek/minimal-madness", "duration": "48:15"}]', '{"monday": true, "tuesday": true, "wednesday": true, "thursday": false, "friday": true, "saturday": true, "sunday": false}', ARRAY['Movement Detroit (Annual)', 'Marble Bar (Fridays)'], ARRAY['Detroit Techno Pioneer Award', 'Resident Advisor Top 100 DJs']),

('protaxia', 'Alex Rodriguez', 'PROTAXIA', 'Bass music specialist known for heavy drops and mind-bending visuals. Creates unforgettable experiences.', '/bass-dj-protaxia-led.png', ARRAY['Dubstep', 'Bass', 'Trap'], 4, 4.5, 1800, 'Denver, CO', ARRAY['Pioneer DDJ-RZ', 'QSC K12.2', 'Akai MPC Live'], '{"instagram": "@protaxia_bass", "soundcloud": "protaxia", "twitter": "@protaxia"}', '[{"title": "Bass Drop Madness", "url": "https://soundcloud.com/protaxia/bass-drop", "duration": "42:30"}, {"title": "Dubstep Destruction", "url": "https://soundcloud.com/protaxia/dubstep-destruction", "duration": "38:45"}]', '{"monday": false, "tuesday": false, "wednesday": false, "thursday": true, "friday": true, "saturday": true, "sunday": false}', ARRAY['Beta Nightclub (Saturdays)', 'Red Rocks (Special Events)'], ARRAY['EDC Denver Performer', 'Bass Music Producer']),

('dillz', 'Dylan Martinez', 'Dillz', 'Multi-genre master who seamlessly blends different styles. Known for creative mashups and crowd-pleasing sets.', '/dj-dillz-mixing.png', ARRAY['House', 'Hip-Hop', 'Latin', 'Pop'], 9, 4.8, 2800, 'New York, NY', ARRAY['Pioneer CDJ-2000NXS2', 'DJM-750MK2', 'Yamaha HS8'], '{"instagram": "@dillz_nyc", "soundcloud": "dillznyc", "twitter": "@dillznyc"}', '[{"title": "NYC Nights", "url": "https://soundcloud.com/dillz/nyc-nights", "duration": "55:20"}, {"title": "Latin Fusion", "url": "https://soundcloud.com/dillz/latin-fusion", "duration": "43:15"}]', '{"monday": true, "tuesday": true, "wednesday": true, "thursday": true, "friday": true, "saturday": true, "sunday": true}', ARRAY['Marquee NY (Thursdays)', 'PHD Rooftop (Sundays)'], ARRAY['NYC Nightlife Awards Best DJ', 'Times Square NYE Performer']),

('fresh', 'Jordan Thompson', 'Fresh', 'Young talent with fresh perspectives on classic sounds. Brings innovation while respecting musical traditions.', '/dj-fresh-turntables.png', ARRAY['House', 'Disco', 'Funk'], 3, 4.4, 1500, 'Chicago, IL', ARRAY['Technics SL-1200MK7', 'Rane Seventy-Two', 'KRK VXT8'], '{"instagram": "@fresh_chi", "soundcloud": "freshchi", "twitter": "@freshchi"}', '[{"title": "Fresh House Vibes", "url": "https://soundcloud.com/fresh/house-vibes", "duration": "40:30"}, {"title": "Disco Revival", "url": "https://soundcloud.com/fresh/disco-revival", "duration": "36:45"}]', '{"monday": false, "tuesday": false, "wednesday": true, "thursday": true, "friday": true, "saturday": true, "sunday": false}', ARRAY['Sound-Bar Chicago (Fridays)', 'Spybar (Saturdays)'], ARRAY['Chicago House Music Festival Performer', 'Rising Star Award 2023']);

-- Insert Venues
INSERT INTO public.venues (name, location, city, image_url, capacity, amenities, preferred_genres, contact_email, contact_phone, website, description) VALUES
('LIV Miami', '4441 Collins Ave', 'Miami', '/luxury-nightclub-liv-miami-interior.png', 2000, ARRAY['VIP Tables', 'Premium Sound System', 'LED Walls', 'Bottle Service'], ARRAY['House', 'EDM', 'Hip-Hop'], 'bookings@livmiami.com', '(305) 674-4680', 'https://livmiami.com', 'World-renowned nightclub in the heart of South Beach'),
('Story Miami', '136 Collins Ave', 'Miami', '/placeholder.svg?height=300&width=400', 3000, ARRAY['Multi-Level Dance Floor', 'Rooftop Terrace', 'State-of-Art Lighting'], ARRAY['EDM', 'Progressive House', 'Techno'], 'events@storymiami.com', '(305) 479-4426', 'https://storymiami.com', 'Massive nightclub with cutting-edge production'),
('Magic City', '241 Forsyth St SW', 'Atlanta', '/placeholder.svg?height=300&width=400', 800, ARRAY['Stage Performance Area', 'VIP Sections', 'Full Bar'], ARRAY['Hip-Hop', 'R&B', 'Trap'], 'booking@magiccityatl.com', '(404) 523-0845', 'https://magiccityatl.com', 'Iconic Atlanta strip club and entertainment venue'),
('1 OAK LA', '9039 Sunset Blvd', 'Los Angeles', '/placeholder.svg?height=300&width=400', 1200, ARRAY['Celebrity Tables', 'Premium Bar', 'Dance Floor'], ARRAY['Hip-Hop', 'Pop', 'EDM'], 'reservations@1oakla.com', '(310) 659-6100', 'https://1oakla.com', 'Exclusive Hollywood nightclub'),
('Beta Nightclub', '1909 Blake St', 'Denver', '/placeholder.svg?height=300&width=400', 1500, ARRAY['Massive Sound System', 'LED Production', 'Multiple Bars'], ARRAY['EDM', 'Dubstep', 'Techno'], 'info@betanightclub.com', '(303) 383-1909', 'https://betanightclub.com', 'Premier electronic music venue in Denver'),
('Marquee NY', '289 10th Ave', 'New York', '/placeholder.svg?height=300&width=400', 2500, ARRAY['Multi-Room Layout', 'Rooftop', 'Premium Sound'], ARRAY['House', 'Hip-Hop', 'Pop'], 'guestlist@marqueeny.com', '(646) 473-0202', 'https://marqueeny.com', 'Iconic NYC nightclub in Chelsea'),
('Sound-Bar Chicago', '226 W Ontario St', 'Chicago', '/placeholder.svg?height=300&width=400', 1000, ARRAY['Underground Vibe', 'Intimate Dance Floor', 'Quality Sound'], ARRAY['House', 'Techno', 'Deep House'], 'info@sound-bar.com', '(312) 787-4480', 'https://sound-bar.com', 'Chicago house music institution');
